# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

launch_config:
  renderer: RaytracedLighting
  headless: true
env_url: ""
working_area_size:
  - 4
  - 4
  - 3
light_config:
  count: 4
  type: "Sphere"
  intensity_min_max: [30000, 40000]
  temperature_min_max: [6000, 7000]
  distant_light_intensity_min_max: [300, 600]
rt_subframes: 4
num_frames: 50
num_cameras: 4
disable_render_products_between_captures: false
camera_collider_radius: 0.2
simulation_duration_between_captures: 0.0
resolution:
  - 720
  - 720
camera_look_at_target_offset: 0.15
camera_distance_to_target_min_max:
  - 0.75
  - 1.5
writer_type: "CocoWriter"
writer_kwargs:
  output_dir: "_out_coco_data"
  rgb: true
  semantic_segmentation: true
  use_common_output_dir: true
  bounding_box_2d_tight: true
  semantic_types: ["class"]

labeled_assets:
  # Labeled assets (scanned from folders with auto-labeling)
  auto_label:
    num: 5
    gravity_disabled_chance: 0.5
    folders:
      - "/home/ubuntu/Workspace/data/ycb/ycb_objects"
    files: []
    regex_replace_pattern: "^[_0-9-]+"
    regex_replace_repl: ""
    scale_min_max: [0.75, 1.25]
    randomize_color: false
    floating: true

shape_distractors_types:
  - capsule
  - cone
  - cylinder
  - sphere
  - cube
shape_distractors_scale_min_max:
  - 0.015
  - 0.15
shape_distractors_num: 150
mesh_distractors_urls:
  - /Isaac/Environments/Simple_Warehouse/Props/SM_CardBoxD_04_1847.usd
  - /Isaac/Environments/Simple_Warehouse/Props/SM_CardBoxA_01_414.usd
  - /Isaac/Environments/Simple_Warehouse/Props/S_TrafficCone.usd
  - /Isaac/Environments/Simple_Warehouse/Props/S_WetFloorSign.usd
  - /Isaac/Environments/Simple_Warehouse/Props/SM_BarelPlastic_B_03.usd
  - /Isaac/Environments/Office/Props/SM_Book_03.usd
  - /Isaac/Environments/Office/Props/SM_Book_34.usd
  - /Isaac/Environments/Office/Props/SM_BookOpen_01.usd
  - /Isaac/Environments/Office/Props/SM_Briefcase.usd
  - /Isaac/Environments/Office/Props/SM_Extinguisher.usd
  - /Isaac/Environments/Hospital/Props/SM_GasCart_01b.usd
  - /Isaac/Environments/Hospital/Props/SM_MedicalBag_01a.usd
  - /Isaac/Environments/Hospital/Props/SM_MedicalBox_01g.usd
  - /Isaac/Environments/Hospital/Props/SM_Toweldispenser_01a.usd
mesh_distractors_scale_min_max:
  - 0.35
  - 1.35
mesh_distractors_num: 75
